[tool.poetry]
name = "models-dev"
version = "0.1.0"
description = ""
authors = ["mszawerd <mikolaj.szawerda@gmail.com>"]
package-mode = false


[tool.poetry.dependencies]
python = "^3.10"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
